# Site settings
title: KUALI
email: kualistories@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stories from and about Malaysians. Have a story to tell? A thought you'd like to share? We'd love to hear from you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kualistories.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      author: "Anonymous"